# Generated by Django 4.0.4 on 2022-05-29 05:39

from django.db import migrations, models
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image_url', models.ImageField(upload_to=myapi.models.upload_to)),
            ],
        ),
    ]
